require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "spec/support/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Max: 50
  Exclude:
    - "spec/**/*"

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 20

RSpec/DescribedClass:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

Capybara/RSpec/PredicateMatcher:
  Enabled: false
